name: PR Build and Publish

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: johnburbridge/johnburbridge-site

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        id: lint
        run: npm run lint

      - name: Build static site
        run: npm run build

      - name: Get base semantic version
        id: base_semver
        run: |
          # Get most recent tag, default to 0.0.0 if none exists
          LATEST_TAG="$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo \"v0.0.0\")"
          BASE_VERSION="${LATEST_TAG#v}"
          echo "BASE_VERSION=${BASE_VERSION}" >> "$GITHUB_ENV"
          echo "base_version=${BASE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Construct PR Version Tag
        id: pr_version
        run: |
          PR_TAG_VERSION="${{ env.BASE_VERSION }}-pr${{ github.event.pull_request.number }}"
          echo "PR_TAG_VERSION=${PR_TAG_VERSION}" >> "$GITHUB_ENV"
          echo "pr_tag_version=${PR_TAG_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # TAGS: Add specific PR version tag and floating pr-NUMBER-latest tag
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PR_TAG_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}-latest
          # LABELS: Add specific PR version as label
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.version=${{ env.PR_TAG_VERSION }}

      - name: Comment on PR with image info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Docker Image Built 🐳

            A new Docker image has been built and pushed to the GitHub Container Registry:

            - Image: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PR_TAG_VERSION }}\`

            You can pull and run it with:
            \`\`\`bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PR_TAG_VERSION }}
            docker run -p 8080:8080 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PR_TAG_VERSION }}
            \`\`\`

            This image will be used for deployment if this PR is merged.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
