name: Validate Workflows

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/**'
      
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup actionlint
        run: |
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- 1.6.25

      - name: Run actionlint
        run: ./actionlint -color